### ISSUE TITLE
the transaction was canceled and the commission was debited

### ISSUE THREAD

**Issue by Yoker26** [galacticcouncil/HydraDX-node#105]
Hello everyone, can someone tell me, when buying on a balancer, the transaction was canceled, and a commission of $ 100 was written off, what should I do ??
https://etherscan.io/tx/0x5dffc6afbb9883f6cc033785d502f3ad87575a177b2e19d5f98042f0100da6bf

**Comment by jak-pan** [comment]
It means that your slippage tolerance setting in balancer was hit. The price changed more than your limit set in the UI so it got cancelled.
