### ISSUE TITLE
Change sell and buy to in and out

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#111]
Use in and out internally to be consistent and clear. 
Keep sell and buy only for user facing functions.
- [x] amm
- [x] exchange
- [x] wasm https://github.com/galacticcouncil/HydraDX-wasm
- [x] math https://github.com/galacticcouncil/HydraDX-math/issues/5

**Comment by enthusiastmartin** [comment]
All done.
