### ISSUE TITLE
Weights template format

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/HydraDX-node#116]
There is hbs template in the .maintain directory which currently does not follow same formatting guidelines.

**Comment by sunnysgithub** [comment]
Regarding the bugs in line 22 and 24: Is it possible that {{cmd.highest_range_values}} and {{cmd.db_cache}} are moved to a new line when saving. I think this is caused by rustfmt. I was able to reproduce it in visual studio code.

**Comment by sunnysgithub** [comment]
Sorry it's not caused by rustfmt. It is a hbs file. But i think that Visual Studio Code moves it to a new line because of a line length constraint.

**Comment by enthusiastmartin** [comment]
> Regarding the bugs in line 22 and 24: Is it possible that {{cmd.highest_range_values}} and {{cmd.db_cache}} are moved to a new line when saving. I think this is caused by rustfmt. I was able to reproduce it in visual studio code.

This was actually already fixed by the latest changes merged to master last night.

So only formatting.
