### ISSUE TITLE
Upgrade bench tool

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#119]
- [x] Create storage heavy benchmark (can be inspired by actual substrate benchmark)
- [x] Dump bench details after failed benchmark
- [x] Rerun once if some failed and some ok
- [ ] Automatic weight update on benchbot run
- [x] Show something that resembles progress since it's running very long now (maybe we can split build and test phases?)
- [x] Add percentage results
- [ ] Increase verbosity
- [ ] Show system info

**Comment by jak-pan** [comment]
Maybe we can create a workflow that runs benchtool and if deviation is more than x % it suggest rerunning benchmarks?
Also if you touch benchmark file we should re-run benchmarks. (Both of these might be a new issue for somebody to try to help with)

**Comment by enthusiastmartin** [comment]
> Maybe we can create a workflow that runs benchtool and if deviation is more than x % it suggest rerunning benchmarks?
> Also if you touch benchmark file we should re-run benchmarks. (Both of these might be a new issue for somebody to try to help with)

I was actually thinking that we can use this tool to run the benchmarks too ( so the bench bot would use this instead of directly calling the craze cargo run command to generate weights )

And if deviation is X% it would directly update the weights ( as it already has all the new information - no need to rerun again), and it can also update the ref values.

**Comment by jak-pan** [comment]
Can we use this? https://pypi.org/project/system-query/

**Comment by enthusiastmartin** [comment]
> Can we use this? https://pypi.org/project/system-query/

sure. we can add a possibilty to dump system info.

**Comment by jak-pan** [comment]
> > Can we use this? https://pypi.org/project/system-query/
> 
> sure. we can add a possibilty to dump system info.

It would be cool if we could autogenerate a list of supported machines (or cpus@freq) like this one with % difference compared to baseline.

https://docs.google.com/spreadsheets/d/1is4y04hTtQzlgDDjH6KFKA6jmwWSj2Phdmgg_Duu_Bs/edit?usp=sharing

**Comment by enthusiastmartin** [comment]
I think - we can move this issue to the bench-wizard repository. This tool has been made as a standalone cli tool and it is no longer part of the main hydradx-node repository.

**Comment by jak-pan** [comment]
Yes but we should link to this issue and open the bench wizard as public repo 🧙 @enthusiastmartin

**Comment by enthusiastmartin** [comment]
> Yes but we should link to this issue and open the bench wizard as public repo 🧙 @enthusiastmartin

Already public. I'll handle the issues.
