### ISSUE TITLE
Bug: Strong enough machines don't pass benchmark

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#127]
Even after #9bccc8d7ca572f490a3cbd790be3863c022fa933 especially exchange benchmark. Maybe we need to re-bench?

**Comment by enthusiastmartin** [comment]
Weights and ref values are not yet correctly updated on the master.

They're all being updated in #119 as references values needs to be adjusted too.

**Comment by jak-pan** [comment]
Testing...

**Comment by jak-pan** [comment]
Looks like fixed. Closing now.
