### ISSUE TITLE
Bug: Claim benchmarking test

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/HydraDX-node#137]
Claims benchmarking test is currently failing with NoClaimOrAlreadyClaimed.

Would be good to sort it out.

**Comment by green-jay** [comment]
@enthusiastmartin solved here? https://github.com/galacticcouncil/HydraDX-node/pull/136

**Comment by enthusiastmartin** [comment]
> @enthusiastmartin solved here? #136

No, if you run the benchmarks test for the claim pallet - it fails. I could not figure it exactly, hence this bug issue. I believe that it is just a problem with correct address and account in that test. I'd leave it up to you as you know how to set it up quickly.

**Comment by green-jay** [comment]
fix https://github.com/galacticcouncil/HydraDX-node/pull/142
