### ISSUE TITLE
Add runtime upgrade and compatibility tests to workflow

### ISSUE THREAD

**Issue by martinfridrich** [galacticcouncil/HydraDX-node#138]
- [ ] add test for backward compatibility - try to run build against current chain
- [ ] add runtime upgrade test and prepare to run integration test with halva

**Comment by lumir-mrkva** [comment]
@martinfridrich we already have runtime upgrade test in parachain, do we still need anything from this issue?

**Comment by martinfridrich** [comment]
This issue was about testing runtime upgrade with fork-ed chain and integrations tests. It probably can be closed, we decided to go different direction.
