### ISSUE TITLE
Postpone financial slashing

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#145]
Postpone financial slashing to maximum viable time < bond duration

**Comment by lumir-mrkva** [comment]
slashing shouldn't be disabled completely, just not applied #185

**Comment by jak-pan** [comment]
Yes this is the case. It's unclear from this issue, but we discussed this on a call. And it's part of #184 Slashes are still applied, nominators get kicked from the nomination set and offences are logged. We just don't want somebody to lose money in the first parts of testnet. I think that the punishment by removing nominations is good enough for people to behave correctly.
