### ISSUE TITLE
Add workflow for SemVer checks

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#152]
We should bump cargo.toml of specific changed pallet, runtime, and spec / implementation versions when new changes are being merged to the master branch

**Comment by lumir-mrkva** [comment]
this could be useful https://github.com/rust-lang/rust-semverver

**Comment by lumir-mrkva** [comment]
related https://github.com/galacticcouncil/Basilisk-node/pull/209

**Comment by lumir-mrkva** [comment]
already done in parachain
