### ISSUE TITLE
Test staking 

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#154]

**Comment by green-jay** [comment]
Tested manually in PolkadotJS. Overall lgtm

**Checked:**

Validator
- [ ] Apply for validator set
- [ ] Validate
- [ ] Bond/unbond
- [ ] Reward payout
- [ ] Add commision
- [ ] Chill

Nominator
- [ ] Nominate validator
- [ ] Bond/unbond
- [ ] Reward payout
- [ ] Chill

1. force_era: Forcing should be probably changed (to use default NotForcing?)
2. should there be weights added for this (as well as other) pallets?
3. add minimal stake/bond amount?
4. not sure about the current settings of min. validaror count and validator counts (initial authorities count/*2)
5. reward curve parameters adjustment should be done once we figure them out and agree on it

**Comment by green-jay** [comment]
TAT done. The reward curve sketched in Desmos+Excel, discussed, approved and deployed in #173
