### ISSUE TITLE
refactor: consolidate pallet event names

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/HydraDX-node#180]
### Description
Event names should be in the style of `AddedLiquidity` instead of `LiquidityAdded` or `AddLiquidity`.

### Actual solution
There is a mix of these styles. Some pallets use `Added`, some `Add` and some have both.

### Expected solution
One style of event names everywhere. Past Tense .

**Comment by jareknowotka** [comment]
Hi, shouldn't event names be in past-tense, as something that happened? I think that's the intention and convention acc. to the pallet documentation. That would be in-line with general DDD convention, where events name reflect business logic. Since naming can get tricky, I'm happy to track down all the events and document them. Would that be helpful?

```
// Events are a simple means of reporting specific conditions and circumstances
// that have happened that users, Dapps and/or chain explorers would find
// interesting and otherwise difficult to detect.
```

https://substrate.dev/docs/en/knowledgebase/runtime/pallets#skeleton-of-a-pallet

**Comment by enthusiastmartin** [comment]
> 
> 
> Hi, shouldn't event names be in past-tense, as something that happened? I think that's the intention and convention acc. to the pallet documentation. That would be in-line with general DDD convention, where events name reflect business logic. Since naming can get tricky, I'm happy to track down all the events and document them. Would that be helpful?
> 
> ```
> // Events are a simple means of reporting specific conditions and circumstances
> // that have happened that users, Dapps and/or chain explorers would find
> // interesting and otherwise difficult to detect.
> ```
> 
> https://substrate.dev/docs/en/knowledgebase/runtime/pallets#skeleton-of-a-pallet

Yes, after some discussions, we go with the past tense in form of `AddedLiquidity`. Details above already updated.

**Comment by jareknowotka** [comment]
Thanks, once changed, would that be a breaking change? Anything relies on these events?

**Comment by jak-pan** [comment]
> Thanks, once changed, would that be a breaking change? Anything relies on these events?

Yes. Anything that changes data structures that are put into blockchain is breaking change.
