### ISSUE TITLE
Add custom balance pallet for treasury

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#182]
For treasury to work, we'll need to create a custom balances pallet, without user callable functions, that will be used to transfer balances between the treasury and users.

**Comment by apopiak** [comment]
You could just do call filtering [here](https://github.com/galacticcouncil/HydraDX-node/blob/77cebb51e4a2f29bbde84d3a9a2753d1de76db36/runtime/src/lib.rs#L166)?

**Comment by jak-pan** [comment]
> You could just do call filtering [here](https://github.com/galacticcouncil/HydraDX-node/blob/77cebb51e4a2f29bbde84d3a9a2753d1de76db36/runtime/src/lib.rs#L166)? (so move Balances to `false` section below)

> You could just do call filtering [here](https://github.com/galacticcouncil/HydraDX-node/blob/77cebb51e4a2f29bbde84d3a9a2753d1de76db36/runtime/src/lib.rs#L166)? (so move Balances to `false` section below)

No. It's not possible to do anything when there is call filter, I spent almost a day debugging this and trying to find different way, resulting in this:
https://github.com/paritytech/substrate/pull/8517

 We need balance transfers for treasury proposals and also as a sudo account for giving dust amounts to people that locked themselves by bonding everything. Unfortunately after some update it's no longer possible when the filter is set to false.

**Comment by jak-pan** [comment]
I tried to do this in signedExtra, unfortunately there's no way to know if the origin is root since there is no root in signed extra.

**Comment by jak-pan** [comment]
Done
