### ISSUE TITLE
Automatically revert slashes in Snakenet

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/HydraDX-node#185]
Testnet slashes should be still tracked, but not applied. Therefore they should be automatically reverted before the grace period.

### Context
We want to have the testing environment as close as possible, therefore we want to test slashing as well, but we don't want to apply penalties. We should maybe even reward those testing and exploring slashing conditions somehow.

### Possible Implementation
A couple of implementation options comes to mind 
- bot that would automatically send sudo transactions (possibly batched) to revert slash
- extrinsic applied automatically on the end of an era in runtime

**Comment by jak-pan** [comment]
I'd close this for now as this happens very occasionally and it's not hard to cancel manually.
