### ISSUE TITLE
Prepare re-genesis script

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#192]
- [x] Get all valid chain data
- [x] Inject last block and genesis hash of old chain into new chain
- [x] Change protocolId

**Comment by lumir-mrkva** [comment]
where we will store the block and genesis hash of the former chain? 

create special pallet with storage for it?
`map gen -> (lastBlockHash, genesisHash)`

**Comment by jak-pan** [comment]
We can do a system.remark or this. Maybe this way, we could let the old chain run (blocking all txs) and insert last genesis hash after the launch>?

**Comment by jak-pan** [comment]
Done.
