### ISSUE TITLE
Normalize manifests of cargo package files

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/HydraDX-node#193]
Manifests currently don't contain accurate information.

We should make sure that it contains correct metadata:
- most packages should have actual license "Apache-2.0", not "Unlicence"
- homepage should be `hydradx.io`
- there always should be some description
- authors should have contact attached
- readme link
- order should be consistent, sorted by the importance of metadata

### Example
```
[package]
name = "hydra-dx-build-script-utils"
version = "3.0.0"
description = "Crate with utility functions for `build.rs` scripts."
authors = ["GalacticCouncil <hydradx@galacticcouncil.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://hydradx.io"
repository = "https://github.com/galacticcouncil/HydraDX-node"
readme = "README.md"
```

**Comment by lumir-mrkva** [comment]
check whenever or not this is still an issue

**Comment by gflow33** [comment]
Can I attempt this?

**Comment by lumir-mrkva** [comment]
> Can I attempt this?

sure 👍

**Comment by gflow33** [comment]
> > Can I attempt this?
> 
> sure +1
Please how do I fill in the "description" field in the manifest? I have no idea on how to describe the functions

**Comment by lumir-mrkva** [comment]
> > > Can I attempt this?
> > 
> > 
> > sure +1
> 
> Please how do I fill in the "description" field in the manifest? I have no idea on how to describe the functions

if there is nothing already, just keep it empty and please link it to me and I will fill it

**Comment by gflow33** [comment]
I submitted a pr. Did I make any mistakes

**Comment by lumir-mrkva** [comment]
@gflow33 fixed this
