### ISSUE TITLE
Create test that runs the chain and checks if it builds blocks.

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#240]
We need such test for every runtime config. After building the node spin it up with all the params and check if it builds few blocks and finalizes. This will need to have different config for different types of chain.

**Comment by jak-pan** [comment]
Already completed?

**Comment by lumir-mrkva** [comment]
no, but we have something similar for basilisk, where we are testing the inclusion of block into relay chain

**Comment by lumir-mrkva** [comment]
connect to the rpc and watch new blocks

https://github.com/galacticcouncil/Basilisk-node/blob/master/scripts/wait-for-inclusion/index.js#L34

**Comment by lumir-mrkva** [comment]
superseeded by parachain inclusion/runtime upgrade. we wont do any test like this for solo chain anymore
