### ISSUE TITLE
Add minimal pool limit, minimal trade limit and pool existential limit

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#28]
These should be setup so that users cannot abuse the system. We should also have minimal pool creation limit / existential limit because the integer math starts to break at some point. Also we don't want to hold very small pools that are blocking other pools because they are very volatile. (something in range of 100-1000 should be ok for math)

Inspiration here:
https://github.com/galacticcouncil/HydraDX-node/pull/27/files

Some progress was also made in #91

**Comment by RoboRambo** [comment]
**1. Minimal Pool Creation Limit (MP):**

The minimal amount of assets needed to create a pool.

One should not be able to create a pool of size 0. Also one should not be able to create a pool with such a small balance that the ability to trade is restricted to a minimum.

Example:
amount of asset_a, asset_b = 1
net worth of assets = $2

If a requested trade exceeds $2, the trade cannot be executed.

Suggestion:
MP e [100, 101, ..., 999, 1000]


**2. Pool Existential Limit (P):**

The minimal amount of assets needed for a pool to exist.

A pool with a balance of 0 should not exist. Also, small pools should not exist (same reasoning as above).

Suggestion:
P e [100, 101, ..., 999, 1000]


**3. Minimal Trade Limit (M):**

The minimal amount of one asset needed to trade.

Suggestion:
M = P / x
x e [10, 100]


Acceptance Criteria:

All of these limits are experimental and:
- should be thought over (especially in combination with the [known limits](https://github.com/galacticcouncil/HydraDX-math/pull/2) of the math crate)
- should be easily tweakable during different testing phases
- prop tests should be expanded/adjusted

**Comment by jak-pan** [comment]
I'd go with 1000 for existential / minimal pool creation limit and 10 as a minimal trade? I think we'll get some more tuning from edge test cases.

**Comment by enthusiastmartin** [comment]
This has been done on Basislisk . All pallets move there. 

When HydraDX repo uses pallets from Basilisk (#287 ) - the limits will come along. 

@jak-pan  Can we therefore close this issue?

**Comment by jak-pan** [comment]
yes
