### ISSUE TITLE
Bug: Accounts that were un-bonding during re-genesis are locked.

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-node#280]
Accounts such as 7KZaTmriQDAcKAF9xbGnxQQksseZSzcPTX3BdkKxPwzF7Y8B that were unbonding their tokens during re-genesis are now locked, since we couldn't transfer the information about staking and unbonding schedules to the new chain due to era and session mismatch. We should get a list of such accounts and write a script that will batch unbond them.

<img width="302" alt="Screenshot 2021-06-14 at 12 17 17" src="https://user-images.githubusercontent.com/3409250/121877587-0fe60800-cd0b-11eb-93fc-a9175f0e62f7.png">

**Comment by wagonwheelss** [comment]
I am also stuck in this situation (

**Comment by wagonwheelss** [comment]
> Accounts such as 7KZaTmriQDAcKAF9xbGnxQQksseZSzcPTX3BdkKxPwzF7Y8B that were unbonding their tokens during re-genesis are now locked, since we couldn't transfer the information about staking and unbonding schedules to the new chain due to era and session mismatch. We should get a list of such accounts and write a script that will batch unbond them.
> 
> <img alt="Screenshot 2021-06-14 at 12 17 17" width="302" src="https://user-images.githubusercontent.com/3409250/121877587-0fe60800-cd0b-11eb-93fc-a9175f0e62f7.png">

I am also stuck in this situation (

**Comment by Hedgecr** [comment]
7NakBh7FhckZX63La4s4FSszNRPXryRuuyP6mfgokpT8abZf - 

I have the same problem
a lot of time has passed (

**Comment by SaNycHJN** [comment]
I also have same problem. My 10.000 HDX coins blocked for several months.
I can't steak and I can't take my coins back. My Account 7NSGubcW8Yobh1RMVKJs2UtBRnVGVztwaYWunqvZRwuahuLQ
ALEXHYDRADXQ (EXTENSION).This is a very sad situation. And I don't understand where was my mistake.

**Comment by wagonwheelss** [comment]
When can we expect a solution to the problem? I want to stake,  but all coins are locked (( My address:
7MStThEUx6VVXWGwpp4UMSoehgojyPvu6t5yrkFmKMPLB6QN

**Comment by jak-pan** [comment]
> @jak-pan When can we expect a solution to the problem? I want to stake, but all coins are locked (( My address:
> 7MStThEUx6VVXWGwpp4UMSoehgojyPvu6t5yrkFmKMPLB6QN

Sorry guys, this was because of one of the two things. 

1/ You or somebody created a voting proposal and you or somebody else has voted / locked funds to do so.
2/ You unbonded your tokens.

Both of these actions could have left you in a locked state. Due to re-genesis, we had to remove this data from chain or it would have caused undefined (or unwanted) behaviour in the new chain. We're working very hard to push the protocol forward, unfortunately these things take a lot of time we couldn't yet dedicate. 

If anybody out there is willing to help with this @cc me, it will certainly be rewarded and we'd love to get you guys up and running. We'll need some generic enough solution, a script, or a list of addresses of such locked accounts anything helps.

**Comment by unordered-set** [comment]
Good evening everyone. I will do my best to resolve this situation. Stay tuned!

**Comment by SaNycHJN** [comment]
Guys, I created a group in telegram HDX Loked coins add please https://t.me/joinchat/zZ8ArtCJd5djYTEy 
Together we are stronger!

**Comment by wagonwheelss** [comment]
> Good evening everyone. I will do my best to resolve this situation. Stay tuned!

This is good news! )

**Comment by wagonwheelss** [comment]
> Good evening everyone. I will do my best to resolve this situation. Stay tuned!
@SaNycHJN @jak-pan 

How are things going guys? When will tokens be unlocked?

**Comment by SaNycHJN** [comment]
> > Good evening everyone. I will do my best to resolve this situation. Stay tuned!
> > @SaNycHJN @jak-pan
> 
> How are things going guys? When will tokens be unlocked?

I don't know man. Hopefully this year.

**Comment by wagonwheelss** [comment]
@unordered-set , how is the solution to the problem going?  I already want to stake my coins. 😕

**Comment by unordered-set** [comment]
Just a raw estimate - we are half of a way there. Some technical issues didn't allow us to resolve the issue last week.

**Comment by iMiroslav** [comment]
I took the Account Stacking Ledger from GEN2 chain and found unbonding balances, then I took the Account Stacking Ledger from GEN3 and subtracted active from the total staking balance. If the difference is the same as unbonding balance in GEN2 this could be proof of the funds locked in Nirvana. 

For Gen 1 I did the very same analysis as between chains Gen2 and Gen3. The result is pretty straightforward. If anybody unbonded the funds in Gen1 the information in the Account Ledger was moved into Gen2. In Gen2 it can be recognized easily because there is unlocking era number 672. 


This way I found 61 accounts with 2 535 279.820 locked HDX. The details could be found in the attached file.
[HydraDX_Accounts_with_tokens_in_Nirvana.zip](https://github.com/galacticcouncil/HydraDX-node/files/7020924/HydraDX_Accounts_with_tokens_in_Nirvana.zip)

**Comment by lumir-mrkva** [comment]
@iMiroslav can you also share scripts that generated this dataset?

**Comment by iMiroslav** [comment]
@lumir-mrkva  This script contains all the functions I have to prepare, execute and check the results. There is also simple documentation for most functions. Hope it makes sense :-)
 
https://gist.github.com/iMiroslav/9e2f142bdd93d5f9b3ea7d1431d8b422

**Comment by lumir-mrkva** [comment]
@jak-pan @iMiroslav based on that data, i have generated and tested on fork-off a storage update that reduces stacking locked amount by gen2 unbonding amount, please review it https://github.com/galacticcouncil/fork-off-hydra/tree/gen3-unbound-fix/gen3-unbond-fix. note that script has to be rerun right before sending a transaction to ensure that data will be consistent.

**Comment by jak-pan** [comment]
Accounts have been successfully unlocked (You'll need to post unlock transaction). 🥳  Sorry for the delays it was quite big effort. Thanks everyone involved!
