### ISSUE TITLE
Add pool account address to `IntentionResolvedAMMTrade` event response.

### ISSUE THREAD

**Issue by mckrava** [galacticcouncil/HydraDX-node#302]
Is it possible add pool account address, which has been used for AMM trade, to event response? It would be super useful for indexer application.
https://github.com/galacticcouncil/HydraDX-node/blob/eb67e1e8692fbdf15b953c4b349c93a9a320fb97/pallets/exchange/src/lib.rs#L134

**Comment by lumir-mrkva** [comment]
this will be resolved by #287
