### ISSUE TITLE
Transform storage for parachain runtime

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-node#360]
- [x] make sure we don't have stray data (remove everything not needed)
- [x] make sure we migrate all the data we want (i.e. locks)
- [x] triple all balances (excluding GC and treasury)
- [x] reduce treasury #365
- [x] triple locks if possible ( no locks tripled - locks are removed)
- [x] triple unclaimed hydra lbp claims
- [x] add crowdloans rewards account balance @vgantchev 
- [x] remove staking and democracy locks, decrease consumer count
- [x] transfer remarks
- [ ] create tests for the migration
- [ ] reduce treasury balance to compensate for trippling by 19811951851387994000 (amount determined in https://github.com/galacticcouncil/HydraDX-node/issues/365)

**Comment by jak-pan** [comment]
Closing
