### ISSUE TITLE
HydraDX full parachain runtime

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/HydraDX-node#361]
initial runtime that will be deployed to the shell parachain immediately after storage migration containing all pallets needed for launch of chain, subset of them will have their storage set by migration before runtime upgrade

**Comment by Roznovjak** [comment]
The list (draft) of pallets:

frame_system - already included in the parachain
pallet_randomness_collective_flip - not required
pallet_babe - not required
pallet_timestamp - already included in the parachain
pallet_grandpa - not required
pallet_balances - already included in the parachain
pallet_transaction_payment - already included in the parachain
pallet_sudo - already included in the parachain
pallet_scheduler
pallet_identity
pallet_preimage

// Collator support
pallet_authorship - already included in the parachain
pallet_collator_selection - already included in the parachain
pallet_session - already included in the parachain
pallet_aura - already included in the parachain
cumulus_pallet_aura_ext - already included in the parachain

// Staking related modules
pallet_authorship - already included in the parachain
pallet_staking - not required
pallet_democracy - not required
pallet_election_provider_multi_phase - not required
pallet_treasury - already included in the parachain

pallet_elections_phragmen - not required
Council: pallet_collective
TechnicalCommittee: pallet_collective
pallet_authority_discovery
pallet_im_online
pallet_offences - not required
session_historical
pallet_tips
pallet_utility - already included in the parachain

// ORML related modules
orml_tokens
orml_currencies
orml_vesting

// HydraDX related modules
pallet_claims
pallet_faucet - not required
pallet_transaction_multi_payment
pallet_genesis_history
pallet_relaychain_info - already included in the parachain

// Parachain
cumulus_pallet_parachain_system - already included in the parachain
parachain_info - already included in the parachain
pallet_xcm
cumulus_pallet_xcm
cumulus_pallet_xcmp_queue
cumulus_pallet_dmp_queue
orml_xcm
orml_xtokens
orml_unknown_tokens
