### ISSUE TITLE
Reduce treasury to account for tripled rewards

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/HydraDX-node#365]
rewards from the treasury are tripled too, these payouts have to be subtracted again from treasury

- [x] deployed idexer #353: http://snakenet-indexer.hydration.cloud:4010/console
- [x] sum all tips
- [x] account other treasury payouts - index all transfers from treasury and sum those that went to the tripled accounts

example of querying all balance.Transfer events from treasury account: 
```
query MyQuery {
  substrate_event(
    where: {name: {_eq: "balances.Transfer"}, 
    data: {_contains: {param0: {type: "AccountId", value: "7L53bUTBopuwFt3mKUfmkzgGLayYa1Yvn1hAg9v5UMrQzTfh"}}}}
  ) {
    name
    data
  }
}
```

**Comment by green-jay** [comment]
Sum of all balance.Transfer amounts outgoing from the treasury account
`7L53bUTBopuwFt3mKUfmkzgGLayYa1Yvn1hAg9v5UMrQzTfh`. Plus there should be a filter in the processor for GC destination account:
`7HqdGVRB4MXz1osLR77mfWoo536cWasTYsuAbVuicHdiKQXf`

Repo set up: https://github.com/galacticcouncil/HydraDX-api

Result:
```
{
  "data": {
    "accounts": [
      {
        "totalTransactions": "2456",
        "lastBlock": "4250042",
        "totalSpent": "9905975925693999999",
        "id": "7L53bUTBopuwFt3mKUfmkzgGLayYa1Yvn1hAg9v5UMrQzTfh"
      }
    ]
  }
}
```
As of today 20220309, we would subtract 19811951851387999998 from the treasury in order to make up for tripling.

**Comment by green-jay** [comment]
sanity check:
```
fetch(
    "http://snakenet-indexer.hydration.cloud:4010/v1/graphql",
    {
      method: "POST",
      body: JSON.stringify({
        query: "query q { substrate_event(where: {name: {_eq: \"balances.Transfer\"}, data: {_contains: {param0: {type: \"AccountId\", value: \"7L53bUTBopuwFt3mKUfmkzgGLayYa1Yvn1hAg9v5UMrQzTfh\"}}}}) { name data } }",
        variables: {},
        operationName: "q"
      })
    }
  ).then(r => r.json())
   .then(({data}) => 
      data.substrate_event.reduce((a, {data: {param2: {value}}}) => a + Number(value), 0)
  ).then(console.log)
```
= `9905975925693997000`

**Comment by green-jay** [comment]
indexer and processor totalSpent from treasury match (9905975925693997000)
