### ISSUE TITLE
Create a faucet bot

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/HydraDX-node#367]
We need to investigate how to setup a bot that would throttle & authorise interaction with our faucet palette.

Acala uses their own discord bot: https://github.com/AcalaNetwork/faucet-bot, we can probably re-use it with our own palette.

- [ ] what tokens do you get?
- [ ] do we reuse our faucet pallet?

**Comment by lumir-mrkva** [comment]
already done in https://github.com/galacticcouncil/Faucet-bot
