### ISSUE TITLE
Upgrade parachain to Polkadot 0.9.16

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/HydraDX-node#368]
same revisions as snakenet to ensure storage compatibility

target branch: **hydra-parachain** https://github.com/galacticcouncil/HydraDX-node/tree/hydra-parachain

**Comment by Roznovjak** [comment]
@lumir-mrkva same revisions as in the latest release? https://github.com/galacticcouncil/HydraDX-node/releases/tag/v11.2.0
