### ISSUE TITLE
Incomplete nirvana compensation

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/HydraDX-node#378]
It seems that only first 11 out of 61 accounts were reimbursed for nirvana lock.

Block with preimage: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Farchive.snakenet.hydradx.io#/explorer/query/2894400

List for reimbursements: [compensationdata.csv](https://github.com/galacticcouncil/HydraDX-node/files/8244260/compensationdata.csv)

We should reprocess and reimburse the remaining 51 accounts.

**Comment by lumir-mrkva** [comment]
@SimonKraus can you take care of this?

**Comment by SimonKraus** [comment]
ForSure!  @lumir-mrkva
