### ISSUE TITLE
Fee's for execution goes to Treasury

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-node#388]
currently native token fees are burned https://github.com/galacticcouncil/warehouse/blob/main/transaction-multi-payment/src/lib.rs#L394

**Comment by Roznovjak** [comment]
Is this issue related only to fees paid for `set_currency`?

**Comment by Roznovjak** [comment]
Already done. Fee + tip goes to Treasury.
https://github.com/galacticcouncil/HydraDX-node/blob/d4801976c7e1dc1c0d6ced0b7c657b4a1a967d1a/runtime/hydradx/src/lib.rs#L318

https://github.com/galacticcouncil/warehouse/blob/d5b8001d90f974f165cf1bfcea0775cfe4340f6b/transaction-multi-payment/src/lib.rs#L454

https://github.com/galacticcouncil/HydraDX-node/blob/d4801976c7e1dc1c0d6ced0b7c657b4a1a967d1a/runtime/hydradx/src/lib.rs#L702
