### ISSUE TITLE
Add NFT pallet to runtime

### ISSUE THREAD

**Issue by lumir-mrkva** [galacticcouncil/HydraDX-node#394]
Omnipool and its LM rely on NFT traits for creating position instances, these traits are implemented in the `pallet_nft` currently used by the Basilisk.

- [x] move pallet nft to the warehouse
- [x] add warehouse pallet nft to the hydra parachain runtime

this changes are not concerning snakenet and should be done in branch `add_pallets` until that gets merged into `hydra-parachain`

**Comment by jak-pan** [comment]
We'll also need it for liquidity mining. As a side-note I would forbid user creation of NFTs on Hydra for now as this is what Basilisk is for.

**Comment by green-jay** [comment]
hydra node needs to be upgraded to v0.9.17 first

**Comment by enthusiastmartin** [comment]
it was done as part of omnipool runtime integration #466
