### ISSUE TITLE
Bug: [Audit_RV] Incorrect imbalance update in pool initialization

### ISSUE THREAD

**Issue by virgil-serbanuta** [galacticcouncil/HydraDX-node#429]
The imbalance caused by the stable asset is added twice, while the imbalance caused by the native asset is ignored.

### Description

In initialize_pool (pallets/omnipool/src/lib.rs), recalculate_imbalance is called twice, and, each time after that, update_imbalance is being called. However, the second time this happens, the result from recalculate_imbalance seems to be mostly ignored (except for error checking), and update_imbalance is called with the same value as the first time.

According to the Discord discussion about this, currently the imbalance delta is 0 in both cases above, so this should not matter much.

Discord discussion: https://discord.com/channels/882700370307067966/1001114717827366913/1002461686034350130
Code link: https://github.com/galacticcouncil/HydraDX-node/blob/8de6222f967cc1bfe120207a775e8f0dc8eb92a5/pallets/omnipool/src/lib.rs#L441-L446

### Possible Fix

Either one of these should be fine

* Remove the imbalance code from initialize_pool (see the Discord discussion)
* Remove only the update_imbalance call and check that recalculate_imbalance returns 0
* Fix the second update_imbalance call.

### Context

Part of the RV audit of the omnipool.

**Comment by enthusiastmartin** [comment]
As already mentioned in the issue description - the imbalance in init pool always results in 0. 

so there is really no need to do calculate and update the imbalance at all. 

This was mainly done to make sure that the same actions are performed for each new added token. 

I will clarify with reseach first - and if ok, the imbalance update will be removed from init pool.

**Comment by enthusiastmartin** [comment]
fixed in #430
