### ISSUE TITLE
[Audit_RV] Assumption not checked: LRNA imbalance is negative.

### ISSUE THREAD

**Issue by virgil-serbanuta** [galacticcouncil/HydraDX-node#434]
`sell` passes the absolute value of the hub asset imbalance to `calculate_sell_state_changes`, ignoring the sign: https://github.com/galacticcouncil/HydraDX-node/blob/8de6222f967cc1bfe120207a775e8f0dc8eb92a5/pallets/omnipool/src/lib.rs#L957 .

This should be safe, since the LRNA imbalance is always negative for now. However, in order to make the code more resilient to future changes, it may be worth adding a check.

**Comment by enthusiastmartin** [comment]
Fixed in #444
