### ISSUE TITLE
[Audit_RV]Suggested Code Improvements

### ISSUE THREAD

**Issue by yanliu18** [galacticcouncil/HydraDX-node#441]
There are a few suggestions to improve the current implementation with regards to more efficient computation, better precision and consistent code style.

### Detailed Description
- [ ] Storage access is better to be in one place. The following implementation is recommended to move `<HubAssetImbalance<T>>::get()` into its function body, similar to functions like `update_tvl()`.
https://github.com/galacticcouncil/HydraDX-node/blob/20c8ac6079b8b3d6f16a9f15e9e43353ea6b9abc/pallets/omnipool/src/lib.rs#L553

### Context
To have cleaner and more consistent code style.
Audit by Runtime Verification

**Comment by enthusiastmartin** [comment]
fixed in #450
