### ISSUE TITLE
[Audit_RV]Bug: Insufficient guarding towards updating HubAssetTradability 

### ISSUE THREAD

**Issue by yanliu18** [galacticcouncil/HydraDX-node#442]
When updating `HubAssetTradability`, there is no checking towards how the tradability could be changed for Hub Asset.
https://github.com/galacticcouncil/HydraDX-node/blob/20c8ac6079b8b3d6f16a9f15e9e43353ea6b9abc/pallets/omnipool/src/lib.rs#L1141

Since the current design only allows HubAsset to be SELL to the pool which is set at the `initialise_pool()` call.
Other tradability like `AddLiquidity` for HubAsset could cause conflicts in the implementation.

It is recommended to return an error if anyone calls `SetAssetTradability()` to assign a possibility other than `SELL` to Hub Asset. It is good to prevent accidental error.
Furthermore, when consider leaving space for future features in the current implementation, it is recommended to weigh the resulting potential conflicts/errors against gains when developing future features. From the security perspective, it is recommended for the current implementation to be faithful to the current design, a.k.a., prevent conflicts/errors as much as possible.

### Description
For example, if the `AddLiquidity` is to be set to HubAsset, then the `AddLiquidity()` interface might not work for HubAsset, since the precondition checking for `Assets.contains_key(HubAssetId)` would not pass. 
Furthermore, if HubAsset is to be added to Assets to satisfy the condition checking, then in the Omnipool’s state mode, we have both state variables `HubAssetTradability`/ `TotalTVL` etc. and `AssetDetails` struct in Assets to track the settings of Hub Asset, that would easily causing in-consistency problems which would further lead to incorrect calculation and economic loss.

### Expected Behavior
Return an error when setting `HubAssetTradability` to a state other than `SELL`

### Actual Behavior
`HubAssetTradability` can be set to any tradability state.

### Context
Audit by Runtime Verification

**Comment by enthusiastmartin** [comment]
fixed in #457
