### ISSUE TITLE
[Audit_RV]Bug: Some condition checking in the specification is not implemented.

### ISSUE THREAD

**Issue by yanliu18** [galacticcouncil/HydraDX-node#452]
The specification requires some condition checking such as the shares to be withdrawn and amount to be swapped greater than 0, it is not checked in corresponding operations.

### Description
- [ ] Specification requires only registered asset can be added to the pool, however in operation `initialize_pool()`, it is not checked if `StableCoinAssetId` exists in AssetRegistry.
https://github.com/galacticcouncil/HydraDX-node/blob/16cdbcf25ef2f1dac5c3569d8cd44cc028ec4076/pallets/omnipool/src/lib.rs#L364
Note that, `HDXAssetId`  is registered at genesis. Furthermore, since `Omnipool::Assets` and `AssetRegistry` are managed separately, they do not imply each other.

- [ ] The amount to be added should be greater than 0 as specification document requires.
https://github.com/galacticcouncil/HydraDX-node/blob/16cdbcf25ef2f1dac5c3569d8cd44cc028ec4076/pallets/omnipool/src/lib.rs#L601
The condition checked above does not guarantee `amount >0`

- [ ] The amount of shares to be removed should be greater than 0.
https://github.com/galacticcouncil/HydraDX-node/blob/16cdbcf25ef2f1dac5c3569d8cd44cc028ec4076/pallets/omnipool/src/lib.rs#L734

**Comment by enthusiastmartin** [comment]
fixed in #458 and #459
