### ISSUE TITLE
Bug: enable --relay-chain-rpc-url flag

### ISSUE THREAD

**Issue by ilhanu** [galacticcouncil/HydraDX-node#492]
### Description
Wanted to test the `--relay-chain-rpc-url` flag for collator in the parachain node. 

### Expected Behavior
The parchain should sync

### Actual Behavior
Node crashes/panics

### Steps to Reproduce
```
ExecStart=/usr/local/bin/hydradx \
    --name "Staker Space" \
    --prometheus-external \
    --base-path /var/lib/hydradx \
    --collator \
    --relay-chain-rpc-url ws://localhost:9944 or link to private/public rpc
```

### Context
Was trying to create a collator without a maintain a local relay-chain db

### Your Environment
Linux  5.4.0-121-generic #137-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

Further logs:

```
Dec 30 08:20:50  [914307]: ====================
Dec 30 08:20:50  [914307]: Version: 14.0.0-3078721 runtime 115.0.0 node 8.3.0 x86_64-linux-gnu
Dec 30 08:20:50  [914307]:    0: sp_panic_handler::set::{{closure}}
Dec 30 08:20:50  [914307]:    1: std::panicking::rust_panic_with_hook
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:702:17
Dec 30 08:20:50  [914307]:    2: std::panicking::begin_panic_handler::{{closure}}
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:588:13
Dec 30 08:20:50  [914307]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/sys_common/backtrace.rs:138:18
Dec 30 08:20:50  [914307]:    4: rust_begin_unwind
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:584:5
Dec 30 08:20:50  [914307]:    5: core::panicking::panic_fmt
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/panicking.rs:142:14
Dec 30 08:20:50  [914307]:    6: core::panicking::panic_display
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/panicking.rs:72:5
Dec 30 08:20:50  [914307]:    7: core::panicking::panic_str
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/panicking.rs:56:5
Dec 30 08:20:50  [914307]:    8: core::option::expect_failed
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/option.rs:1874:5
Dec 30 08:20:50  [914307]:    9: hydradx::service::start_node_impl::{{closure}}
Dec 30 08:20:50  [914307]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Dec 30 08:20:50  [914307]:   11: std::thread::local::LocalKey<T>::with
Dec 30 08:20:50  [914307]:   12: tokio::park::thread::CachedParkThread::block_on
Dec 30 08:20:50  [914307]:   13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
Dec 30 08:20:50  [914307]:   14: hydradx::command::run
Dec 30 08:20:50  [914307]:   15: hydradx::main
Dec 30 08:20:50  [914307]:   16: std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 30 08:20:50  [914307]:   17: std::rt::lang_start::{{closure}}
Dec 30 08:20:50  [914307]:   18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/ops/function.rs:280:13
Dec 30 08:20:50  [914307]:       std::panicking::try::do_call
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:492:40
Dec 30 08:20:50  [914307]:       std::panicking::try
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:456:19
Dec 30 08:20:50  [914307]:       std::panic::catch_unwind
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panic.rs:137:14
Dec 30 08:20:50  [914307]:       std::rt::lang_start_internal::{{closure}}
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/rt.rs:128:48
Dec 30 08:20:50  [914307]:       std::panicking::try::do_call
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:492:40
Dec 30 08:20:50  [914307]:       std::panicking::try
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:456:19
Dec 30 08:20:50  [914307]:       std::panic::catch_unwind
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panic.rs:137:14
Dec 30 08:20:50  [914307]:       std::rt::lang_start_internal
Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/rt.rs:128:20
Dec 30 08:20:50  [914307]:   19: main
Dec 30 08:20:50  [914307]:   20: __libc_start_main
Dec 30 08:20:50  [914307]:   21: _start
Dec 30 08:20:50  [914307]: Thread 'main' panicked at 'Command line arguments do not allow this. qed', node/src/service.rs:415
Dec 30 08:20:50  [914307]: This is a bug. Please report it at:
Dec 30 08:20:50  [914307]:         https://github.com/galacticcouncil/HydraDX-node/issues
```

**Comment by Jozzq** [comment]
> ### Description
> 
> Wanted to test the `--relay-chain-rpc-url` flag for collator in the parachain node. 
> 
> 
> 
> ### Expected Behavior
> 
> The parchain should sync
> 
> 
> 
> ### Actual Behavior
> 
> Node crashes/panics
> 
> 
> 
> ### Steps to Reproduce
> 
> ```
> 
> ExecStart=/usr/local/bin/hydradx \
> 
>     --name "Staker Space" \
> 
>     --prometheus-external \
> 
>     --base-path /var/lib/hydradx \
> 
>     --collator \
> 
>     --relay-chain-rpc-url ws://localhost:9944 or link to private/public rpc
> 
> ```
> 
> 
> 
> ### Context
> 
> Was trying to create a collator without a maintain a local relay-chain db
> 
> 
> 
> ### Your Environment
> 
> Linux  5.4.0-121-generic #137-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
> 
> 
> 
> Further logs:
> 
> 
> 
> ```
> 
> Dec 30 08:20:50  [914307]: ====================
> 
> Dec 30 08:20:50  [914307]: Version: 14.0.0-3078721 runtime 115.0.0 node 8.3.0 x86_64-linux-gnu
> 
> Dec 30 08:20:50  [914307]:    0: sp_panic_handler::set::{{closure}}
> 
> Dec 30 08:20:50  [914307]:    1: std::panicking::rust_panic_with_hook
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:702:17
> 
> Dec 30 08:20:50  [914307]:    2: std::panicking::begin_panic_handler::{{closure}}
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:588:13
> 
> Dec 30 08:20:50  [914307]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/sys_common/backtrace.rs:138:18
> 
> Dec 30 08:20:50  [914307]:    4: rust_begin_unwind
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:584:5
> 
> Dec 30 08:20:50  [914307]:    5: core::panicking::panic_fmt
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/panicking.rs:142:14
> 
> Dec 30 08:20:50  [914307]:    6: core::panicking::panic_display
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/panicking.rs:72:5
> 
> Dec 30 08:20:50  [914307]:    7: core::panicking::panic_str
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/panicking.rs:56:5
> 
> Dec 30 08:20:50  [914307]:    8: core::option::expect_failed
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/option.rs:1874:5
> 
> Dec 30 08:20:50  [914307]:    9: hydradx::service::start_node_impl::{{closure}}
> 
> Dec 30 08:20:50  [914307]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
> 
> Dec 30 08:20:50  [914307]:   11: std::thread::local::LocalKey<T>::with
> 
> Dec 30 08:20:50  [914307]:   12: tokio::park::thread::CachedParkThread::block_on
> 
> Dec 30 08:20:50  [914307]:   13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
> 
> Dec 30 08:20:50  [914307]:   14: hydradx::command::run
> 
> Dec 30 08:20:50  [914307]:   15: hydradx::main
> 
> Dec 30 08:20:50  [914307]:   16: std::sys_common::backtrace::__rust_begin_short_backtrace
> 
> Dec 30 08:20:50  [914307]:   17: std::rt::lang_start::{{closure}}
> 
> Dec 30 08:20:50  [914307]:   18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/core/src/ops/function.rs:280:13
> 
> Dec 30 08:20:50  [914307]:       std::panicking::try::do_call
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:492:40
> 
> Dec 30 08:20:50  [914307]:       std::panicking::try
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:456:19
> 
> Dec 30 08:20:50  [914307]:       std::panic::catch_unwind
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panic.rs:137:14
> 
> Dec 30 08:20:50  [914307]:       std::rt::lang_start_internal::{{closure}}
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/rt.rs:128:48
> 
> Dec 30 08:20:50  [914307]:       std::panicking::try::do_call
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:492:40
> 
> Dec 30 08:20:50  [914307]:       std::panicking::try
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panicking.rs:456:19
> 
> Dec 30 08:20:50  [914307]:       std::panic::catch_unwind
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/panic.rs:137:14
> 
> Dec 30 08:20:50  [914307]:       std::rt::lang_start_internal
> 
> Dec 30 08:20:50  [914307]:              at rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library/std/src/rt.rs:128:20
> 
> Dec 30 08:20:50  [914307]:   19: main
> 
> Dec 30 08:20:50  [914307]:   20: __libc_start_main
> 
> Dec 30 08:20:50  [914307]:   21: _start
> 
> Dec 30 08:20:50  [914307]: Thread 'main' panicked at 'Command line arguments do not allow this. qed', node/src/service.rs:415
> 
> Dec 30 08:20:50  [914307]: This is a bug. Please report it at:
> 
> Dec 30 08:20:50  [914307]:         https://github.com/galacticcouncil/HydraDX-node/issues
> 
> ```

We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n
@ilhanu

**Comment by Roznovjak** [comment]
Thank you for reporting this issue. It should be resolved in the next release.
