### ISSUE TITLE
Fix Claims and GenesisHistory pallets

### ISSUE THREAD

**Issue by apopiak** [galacticcouncil/HydraDX-node#518]
It seems that pallet-claims and pallet-genesis-history are not part of the workspace and thus their tests are not run.
We should probably add them to the workspace to make sure they run tests.

**Comment by Roznovjak** [comment]
When are the tests not run? Both `cargo test` and `make test` run the tests.

**Comment by apopiak** [comment]
huh, I could swear they didn't execute, very confused o.O
confirmed that they run on master 🤷
