### ISSUE TITLE
Bug: Existential deposit is not respected on swap

### ISSUE THREAD

**Issue by sea212** [galacticcouncil/HydraDX-node#555]
### Description
When trading any token in the Omnipool, the existential deposit of the token that is received is not respected. An account could receive some tokens and be killed immediately.

### Expected Behavior
The Omnipool should return an error and not execute the swap or the user should be warned in the UI.

### Actual Behavior
The Omnipool executes the swap and the account is killed immediately afterwards.

### Possible Fix
The Omnipool queries the `Tokens` pallet and the `AssetRegistry` to verify that the ED constraints are met. This will take two additional reads per swap, which is not ideal. Instead, the HydraDX app UI could perform this check and at least warn the user.

### Steps to Reproduce
1. Execute swap instruction at https://hydradx.subscan.io/extrinsic/0xd20ba5ecc3386eb464316daba11facef735233e99ff6ce4f8f984bcbafc92297

**Comment by jak-pan** [comment]
Yeah this should be handled on UI as it would increase tx cost unnecessarily.

Closing in favor of https://github.com/galacticcouncil/HydraDX-ui/issues/348

**Comment by jak-pan** [comment]
Thank you :)
