### ISSUE TITLE
Wrong price is provided to the `ensure_price` function

### ISSUE THREAD

**Issue by yzhang90** [galacticcouncil/HydraDX-node#566]
The spot price is defined as `LRNA reserve / asset reserve`. The goal of the `ensure_price` is to check that the price difference between spot price and oracle price is within the allowed range around the `oracle` price. which is `| oracle - price | <= oracle * maxDiffAllowed`. However, in the implementation, `asset reserve / LRNA reserve`(which equals to the inverse of the spot price) is passed to the `ensure_price` function:
https://github.com/galacticcouncil/HydraDX-node/blob/6e6e99c8aada2977d37bb2a1756939366a02dd02/pallets/omnipool/src/lib.rs#L674

As the result, the code actually checks that  `| oracle - price | <= price * maxDiffAllowed`, i.e., checking the price difference is within the allowed range of the `spot price`.

**Comment by enthusiastmartin** [comment]
No, they both used correct price in form of : ASSET / LRNA .

it is true that price returned from aset_state.price() call is LRNA/ asset , but this is not used in the price check.

**Comment by yzhang90** [comment]
fixed in #567
