### ISSUE TITLE
Bug: Command line flag for using remote relay chain on Hydra node doesn't work

### ISSUE THREAD

**Issue by pmensik** [galacticcouncil/HydraDX-node#569]
Hello,

I tried to run HydraDX collator with `relay-chain-rpc-url` flag to specify a remote relay chain RPC to be used instead of the embedded one but the node process crashes on startup. 

Here is the full config

```
ExecStart=/usr/local/bin/polkadot \
  --name Polkadotters \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --telemetry-url 'wss://telemetry.hydradx.io:9000/submit/ 0' \
  --base-path '/var/lib/hydradx' \
  --prometheus-external \
  --collator \
  --relay-chain-rpc-url ws://194.163.154.254:9944 \
  ```

And [here](https://pastebin.com/SpptuFfd) is the log describing the error. I can provide more information if needed but I guess the issue is pretty self-explanatory. Is this caused by an older version of Substrate that doesn't support the flag? Is there any plan to add such support? Thank you

**Comment by Roznovjak** [comment]
Thank you for reporting this issue. It should be resolved in the next release.
