### ISSUE TITLE
review and rewrite DCA docs

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-node#595]

**Comment by dmoka** [comment]
Some additional info about the doc

 `i think that is key to explain what "schedule" is and order details as well, more in detail is should be explained what is absolute trade limit and dynamic one (slippage), also "total_amout" should be explained in detail and how it behaves in case of sell/buy and fees etc.`

**Comment by dmoka** [comment]
Also add doc comments around the Schedule object itself

**Comment by dmoka** [comment]
Here is the PR for it https://github.com/galacticcouncil/HydraDX-node/pull/607/files
