### ISSUE TITLE
Bug: Docker image has lower version glibc than the program required

### ISSUE THREAD

**Issue by mikespook** [galacticcouncil/HydraDX-node#665]
When we are attempting to use a more recent HydraDX Docker images, for example, pr-612, pr-652, pr-664, an error arises indicating “version `GLIBC_2.34′ not found.” The last runnable Docker image for us is quite old and couldn't get any peers. 

### Description
With the HydraDX Docker image, reproducing this is straightforward. I anticipate that the following command should directly
 run HydraDX. My environment is a Macbook Pro M1, thus the command line parameter –platform linux/x86_64 is required.

`$ docker run -it --rm --platform linux/x86_64 galacticcouncil/hydra-dx:pr-664`

```
/usr/local/bin/hydradx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/hydradx)
/usr/local/bin/hydradx: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/local/bin/hydradx)
```

### Expected Behavior

With the docker command, the instance should run without trouble.
For example, here is the last known version pr-489 which can be run directly.

`docker run --platform linux/x86_64 galacticcouncil/hydra-dx:pr-489`

```
2023-09-06 21:47:27 HydraDX
2023-09-06 21:47:27 ✌️  version 14.0.0-965e02a5 runtime 121.0.0 node 8.3.0 x86_64-linux-gnu
2023-09-06 21:47:27 ❤️  by GalacticCouncil, 2020-2023
2023-09-06 21:47:27 📋 Chain specification: HydraDX
2023-09-06 21:47:27 🏷  Node name: open-ticket-8378
```

### Actual Behavior

```
/usr/local/bin/hydradx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/hydradx)
/usr/local/bin/hydradx: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/local/bin/hydradx)
```

### Possible Fix

I've written a post about the detail
[Understanding the ‘lib not found’ Error When Running HydraDX on Docker](https://mikespook.com/2023/09/understanding-the-lib-not-found-error-when-running-hydradx-on-docker/)

The easiest fix would be upgrading Ubuntu 21.04 to Ubuntu 22.04. I will make a pull-request.

### Steps to Reproduce

`$ docker run -it --rm --platform linux/x86_64 galacticcouncil/hydra-dx:pr-664`

### Context

We are hosting chain-nodes in the k8s cluster. At the stage, pr-489 can run without trouble. But the instance won't get any peer.

### Your Environment

`$ docker version`

```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.15.0 (93002)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:41 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

`$ docker image ls`

```
REPOSITORY                 TAG       IMAGE ID       CREATED        SIZE
galacticcouncil/hydra-dx   pr-664    6917f50cbfb5   6 days ago     425MB
galacticcouncil/hydra-dx   pr-489    5a75f2884041   8 months ago   406MB
```

**Comment by mrq1911** [comment]
fixed by #666
