### ISSUE TITLE
Investigate PoV sizes

### ISSUE THREAD

**Issue by ordian** [galacticcouncil/HydraDX-node#667]
gm

I wonder if you're aware of the PoV sizes of the blocks produced by both Basilisk on Kusama and HydraDX on Polkadot. Our scraping services show that the PoV contribution of each of your parachain is around 8GB per day, which is more than 1MB per PoV block on average (this is way above any other parachain). 

Are you aware of this or know that might be contributing to the PoV size? (can also probably see the collators logs to confirm)

Given that there not enough extrinsics in the blocks to explain that, is it possible that you for example do some iteration in every block, reading some state? If not, that could indicate a bug in state proof recorder that includes some data it shouldn't.

**Comment by mrq1911** [comment]
i can confirm this, collator is producing 1MB+ proofs for as long i can see in collator logs (couple of months). do you have historical data about PoV size?

**Comment by ordian** [comment]
I can only say it was still the case in July but don't have historical data below that.

**Comment by ordian** [comment]
Might be related: https://github.com/paritytech/polkadot-sdk/issues/1498

**Comment by burdges** [comment]
@cheme do you have a radix 2 flavor of https://github.com/paritytech/trie or whatever somewhere?

**Comment by cheme** [comment]
> @cheme do you have a radix 2 flavor of https://github.com/paritytech/trie or whatever somewhere?

Had this branch from 2020 https://github.com/paritytech/trie/pull/84, but today it is a lot behind current trie crate (probably 1 or 2 days of work to update).

**Comment by mrq1911** [comment]
it looks like we are attaching code wasm in every block proof. i am not sure what causes this behaviaout however

**Comment by cheme** [comment]
Well you are probably using trie_version 0 (maybe state_version), with version 1 the value is not attach to the node and only include if accessed by the runtime. WARNING: switching requires a migration (or warpsync will be broken).

So if using state_version 0, maybe you query an entry close to key ":code" eg ":codex" that would include the node (and its value) at ":code" into your proof.
so any query to key starting with ":code", and some insert or removal of key close to :code (which may result in changing the node prefix at :code and thus touching the node).

> 1st one appears to contain wasm file

yes wasm is in the top trie at key ':code' (utf8 values).
would make sense to trace all runtime access during block processing and try to find what key query can touch ':code' trie node (I don't remember how it can be done but maybe with try-runtime and some logging (cannot check right now), if missing traces can be added on sp-io storage function or sp-state-machine trie accesses directly.

**Comment by enthusiastmartin** [comment]
With stare_version set to 1.

2023-09-18 16:40:12 [Parachain] PoV size { header: 0.1787109375kb, extrinsics: 2.865234375kb, storage_proof: 4.306640625kb }
2023-09-18 16:40:12 [Parachain] Compressed PoV size: 6.330078125kb

So I guess, we should consider migrating.

Would have some details how to do that?

**Comment by cheme** [comment]
There is a link to the md guide and lot of link to different progress on relay chain https://github.com/paritytech/devops/issues/1508#issuecomment-1271565180 .
Note that the migration process for parachain may seems more complicated than for a relay (progress by adding extrinsic in each block manually), to avoid going over the block size (with the automatic process used in relay chain there is always a risk that the content of the chain will include a very big value on top of an already big proof).
But from my point of view a parachain could still audit cautiously its content and assert such scenario will not happen (even possibly run some value migration ahead and skip them afterward in the automatic migration process: but this is not currently coded in the state-migration pallet).
Generally, the migration process is not something complicated, it just requires that every key value in the runtime get written again once (if you look at the state migration automatic process, we just store a progress key and advance a few value at the start of every blocks).

**Comment by mrq1911** [comment]
> There is a link to the md guide and lot of link to different progress on relay chain https://github.com/paritytech/devops/issues/1508#issuecomment-1271565180 .

sry, this link is broken for me, is it in private repo?

**Comment by cheme** [comment]
:facepalm: yes it is a private one, the link to the guide was https://hackmd.io/JagpUd8tTjuKf9HQtpvHIQ (a post refering to it https://forum.polkadot.network/t/state-trie-migration/852).

**Comment by jak-pan** [comment]
Solved by #799 and running migration on wasm
