### ISSUE TITLE
RouterExecuted event is filled incorrectly for buy

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-node#753]
should use 1st asset in instead of last https://github.com/galacticcouncil/HydraDX-node/blob/10bc08ddac1b8cd23bbb64e1e70fdaa98842a508/pallets/route-executor/src/lib.rs#L317

also the check for asset in should be reworked

**Comment by dmoka** [comment]
What is the issue with asset_in check?

**Comment by mrq1911** [comment]
doesn't seem to me that it checks anything really :)

**Comment by mrq1911** [comment]
also please rename the event to `Executed` to distinguish it from the broken event

**Comment by dmoka** [comment]
After further investigations, it was not about wrong `amount_in` in the event, but the the mixed `asset_in` and `asset_out`.

https://github.com/galacticcouncil/HydraDX-node/pull/760

**Comment by dmoka** [comment]
https://github.com/galacticcouncil/HydraDX-node/pull/760
