### ISSUE TITLE
Cannot buy insufficient asset with EVM

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-node#804]
## 2 ways to replicate
use wallet with WETH and EVM transaction dispatch
- buy insufficient asset (throws `UnsupportedCurrency` in dry-run)
- router swap with insufficient asset en route (throws `InsufficientBalance`)

<img width="1507" alt="Screenshot_2024-04-15_at_15 56 15" src="https://github.com/galacticcouncil/HydraDX-node/assets/2580779/aceaa792-d728-4b50-b029-eee346a8520c">

## preliminary investigation
`UnsupportedCurrency` is most likely thrown by `on_funds` handler, because currency set for fee payer is no supported, but the actual accounts have WETH (20) set as their payment currency in fact

**Comment by DuriSK** [comment]
Same issue happens if EVM account is trying to provide liquidity for XYK pool where one of the assets is external asset. 
Adding liquidity for normal assets is working on EVM, and also adding liquidity on substrate account to XYK pools with external asset is working

**Comment by jak-pan** [comment]
Fixed by #805
